# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: name-tests-test
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: check-json
  - id: check-yaml
  - id: check-ast
  - id: check-added-large-files
- repo: https://github.com/crate-ci/typos
  rev: v1.16.26
  hooks:
  - id: typos
